### ISSUE TITLE
今日のタスク（じゅん）

### ISSUE THREAD

**Issue by RairuDev** [H-hidetaka/share_house#10]
#  1月4日のタスク

- [x] 朝の日課
- [ ] 自分の健康アプリを作り終わる
- [x] 筋トレ
- [ ] ER図を作る
- [ ] 機能の確認、画面遷移図の確認
- [ ] 企業確認応募
- [ ] 洗面所掃除
- [x] 瞑想

**Comment by RairuDev** [comment]
頑張ります

**Comment by RairuDev** [comment]
作業始めます

**Comment by RairuDev** [comment]
日課終わりました

**Comment by RairuDev** [comment]
# 1月5日のタスク
- [ ] 朝の日課
- [ ] グラフのところを日本語に言語化
- [ ] デプロイ
- [ ] ER図(ポートフォリオ)
- [ ] ER図(チーム開発)
- [x] 掃除
- [ ] 瞑想
- [x] 筋トレ

**Comment by RairuDev** [comment]
# 1月6日のタスク
- [ ] 本読み終わる
- [ ] 応募10社
- [ ] デプロイ
- [ ] 筋トレ
- [ ] 瞑想
- [ ] 料理を作る

**Comment by RairuDev** [comment]
# 1月7日のタスク
- [ ] 日課
- [ ] タイピング
- [ ] デプロイ
- [ ] 企業検索
- [ ] ER図
- [ ] 筋トレ
- [ ] 掃除
- [ ] 瞑想
- [ ] ER図（共同開発）

**Comment by RairuDev** [comment]
# 1月８日のタスク
- [x] 日課
- [x] タイピング
- [x] デプロイ
- [ ] 企業検索
- [ ] ER図
- [x] 筋トレ
- [x] 掃除
- [x] 瞑想
- [x] 読書
- [ ] 脳トレ

**Comment by RairuDev** [comment]
# 1月9日のタスク
- [x] 日課
- [x] タイピング
- [x] 会員登録のエラーを調査
- [x] インデント直す
- [ ] 企業検索
- [ ] ER図
- [x] 筋トレ
- [x] 掃除
- [x] 瞑想
- [x] 読書
- [ ] 脳トレ

**Comment by RairuDev** [comment]
# 1月10日のタスク
- [x] 日課
- [x] タイピング
- [x] wantedly登録
- [ ] リファクタリング
- [x] 企業検索
- [ ] 日付を直す
- [ ] メンタリング
- [ ] 細かい調整直す
- [x] 筋トレ
- [ ] 掃除
- [ ] 瞑想
- [x] 読書
- [ ] 脳トレ

**Comment by RairuDev** [comment]
# 1月11日のタスク
- [x] 日課
- [x] タイピング
- [ ] リファクタリング
- [ ] cssの調整
- [x] 企業検索
- [ ] 日付を直す（heroku）
- [ ] 細かい調整直す
- [x] 筋トレ
- [ ] 掃除
- [x] 瞑想
- [x] 読書
- [x] 脳トレ

**Comment by RairuDev** [comment]
# 1月12日のタスク
- [x] 日課
- [x] タイピング
- [ ] リファクタリング
- [ ] cssの調整
- [ ] 日付を直す（heroku）
- [ ] 細かい調整直す
- [x] 筋トレ
- [ ] 掃除
- [x] 瞑想
- [ ] 読書
- [ ] 脳トレ

**Comment by RairuDev** [comment]
# 1月14日のタスク
- [ ] 日課
- [x] タイピング
- [ ] リファクタリング
- [ ] エラーメッセージ調整
- [ ] 面接
- [ ] 動画を撮る
- [x] 日付を直す（heroku）
- [x] 筋トレ
- [ ] 掃除
- [ ] 瞑想
- [ ] 読書
- [ ] 脳トレ

**Comment by RairuDev** [comment]
# 1月16日のタスク
- [ ] 日課
- [x] タイピング
- [ ] 動画を撮る
- [ ] 環境構築
- [x] 筋トレ
- [ ] 掃除
- [ ] 瞑想
- [ ] 読書
- [ ] 脳トレ

**Comment by RairuDev** [comment]
# 1月19日のタスク
- [x] 日課
- [x] タイピング
- [ ] 動画を撮る
- [ ] 環境構築
- [ ] 筋トレ
- [ ] 掃除
- [ ] 瞑想
- [ ] 読書
- [ ] ナンパ

**Comment by RairuDev** [comment]
# 1月20日のタスク
- [ ] 日課
- [ ] タイピング
- [ ] 動画を撮る
- [ ] 環境構築
- [ ] 筋トレ
- [ ] 掃除
- [ ] 瞑想
- [ ] 読書
- [ ] ナンパ

**Comment by RairuDev** [comment]
# 1月24日のタスク
- [ ] 日課
- [ ] タイピング
- [ ] 動画を撮る
- [ ] パスワード変更機能
- [x] 筋トレ
- [ ] 掃除
- [ ] 瞑想
- [ ] 読書
- [x] ナンパ

**Comment by RairuDev** [comment]
# 1月25日のタスク
- [ ] 日課
- [x] タイピング
- [ ] 動画を撮る
- [ ] パスワード変更機能
- [x] 筋トレ
- [ ] 掃除
- [ ] 瞑想
- [ ] 読書
- [x] 面接
- [ ] リファクタリング

**Comment by RairuDev** [comment]
# 1月25日のタスク
- [ ] 日課
- [x] タイピング
- [ ] 動画を撮る
- [x] パスワード変更機能
- [x] 筋トレ
- [ ] 掃除
- [ ] 瞑想
- [ ] 読書
- [x] 浅草
- [ ] リファクタリング

**Comment by RairuDev** [comment]
# 1月26日のタスク
- [ ] 日課
- [x] タイピング
- [ ] 動画を撮る
- [ ] 体重グラフを綺麗にする
- [ ] herokuデプロイ
- [ ] 筋トレ
- [ ] 掃除
- [ ] 瞑想
- [ ] 読書
- [ ] リファクタリング

**Comment by RairuDev** [comment]
# 1月26日のタスク
- [ ] 日課
- [x] タイピング
- [ ] 動画を撮る
- [ ] 体重グラフを綺麗にする
- [ ] herokuデプロイ
- [x] 筋トレ
- [ ] 掃除
- [ ] 瞑想
- [ ] 適性栄養量を見直す
- [x] 読書
- [x] TOPページを綺麗にする

**Comment by RairuDev** [comment]
# 1月30日のタスク
- [ ] 日課
- [x] タイピング
- [ ] 動画を撮る
- [ ] listアクションリファクタ
- [x] herokuデプロイ
- [ ] 筋トレ
- [ ] 掃除
- [ ] 瞑想
- [ ] 適性栄養量を見直す
- [ ] 読書
- [ ] TOPページを綺麗にする
- [x] ナンパ

**Comment by RairuDev** [comment]
# 1月31日のタスク
- [ ] 日課
- [x] タイピング
- [ ] 動画を撮る
- [ ] listアクションリファクタ
- [ ] 転職サービス登録
- [ ] 筋トレ
- [ ] コンロ掃除
- [ ] 瞑想
- [ ] 適性栄養量を見直す
- [ ] 読書
- [ ] TOPページを綺麗にする
- [x] ナンパ

**Comment by RairuDev** [comment]
# 2月1日のタスク
- [ ] 日課
- [x] タイピング
- [x] AWS解約
- [x] 筋トレ
- [x] コンロ掃除
- [ ] 自己PR
- [ ] 瞑想
- [ ] カレンダー実装
- [ ] その部分のリファクタ
- [x] 動画撮影
- [x] 読書
- [x] ナンパ

**Comment by RairuDev** [comment]
# 2月２日のタスク
- [ ] 日課
- [ ] タイピング
- [ ] 筋トレ
- [ ] 自己PR
- [ ] 瞑想
- [ ] カレンダー実装
- [ ] その部分のリファクタ
- [ ] 動画撮影
- [ ] 読書

**Comment by H-hidetaka** [comment]
> # 2月２日のタスク
> * [ ]  日課
> * [ ]  タイピング
> * [ ]  筋トレ
> * [ ]  自己PR
> * [ ]  瞑想
> * [ ]  カレンダー実装
> * [ ]  その部分のリファクタ
> * [ ]  動画撮影
> * [ ]  読書
