### ISSUE TITLE
テスト

### ISSUE THREAD

**Issue by RairuDev** [H-hidetaka/share_house#6]
- [ ] aaa

**Comment by RairuDev** [comment]
tes

**Comment by RairuDev** [comment]
#5
直しました

**Comment by H-hidetaka** [comment]
- [ ] #1
- [ ] https://github.com/octo-org/octo-repo/issues/740
- [ ] Add delight to the experience when all tasks are complete :tada:

**Comment by H-hidetaka** [comment]
閉じます
